# Generated by Django 6.0.5 on 2026-06-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('announs', models.CharField(max_length=250, verbose_name='The Announcement')),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
